### ISSUE TITLE
add unit tests in `examples`

### ISSUE THREAD

**Issue by zzsi** [kungfuai/CVlization#54]
Consider adding unit tests in individual workflow examples. These tests ideally are triggered when changes are committed for certain types of files in the particular example directory.

In github actions, a path filter can be used:

```
on:
  push:
    paths:
      - folder1/**
```

This may need to be written for every `test.sh`.
